[package]
name = "gff-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bio_rascal = {path = "../bio-rascal"}
clap = { version = "4.1.1", features = ["derive"] }
clap_complete = "4.1.0"
